### ISSUE TITLE
How to achieve bulkheading with this solution?

### ISSUE THREAD

**Issue by shivamka1** [AlexITC/play-request-tracer#1]
Let's say I have three layers of workflow in an app, namely, "controllers", "services" and "daos". Now I have wish to include bulkheading. In order to achieve so, I may decide to assign different execution context/dispatchers for each of this layers.

My doubt is if this solution would work. How can we propagate MDC across dispatchers?

**Comment by AlexITC** [comment]
It has been a long time since I wrote this library, from what I remember, as long as your controllers and below layers are not singletons, everything should work.

I understand your confusion because other alternatives tend to propagate the context by storing data in the thread local (like request id in this case), which causes issues while switching between execution contexts.

This library doesn't have such issue because it doesn't rely in the thread local but guide dependency injection.

Be aware that this is an experiment that I have never used in any production service, overall the code is very simple but it hasn't been tested extensively.
